// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Autogenerated from the docs/ folder structure (wiki_structure):
  // 00-getting-started, 01-alfa-network, 02-hak5, 03-flipper-zero,
  // 04-sdrlab, 05-acs, 99-admin
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
