// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Autogenerated public sections (excludes internal 99-admin)
  docsSidebar: [
    {type: 'autogenerated', dirName: '00-getting-started'},
    {type: 'autogenerated', dirName: '01-alfa-network'},
    {type: 'autogenerated', dirName: '02-hak5'},
    {type: 'autogenerated', dirName: '03-flipper-zero'},
    {type: 'autogenerated', dirName: '04-sdrlab'},
    {type: 'autogenerated', dirName: '05-acs'},
  ],
};

export default sidebars;
